package com.obm.hy.export.bean;

import android.os.Parcel;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "FILE_FORMAT".
 */
public class FileFormatBean {

    private Long id;

    private String ctype;
    private Integer nseqno;
    private String cfieldName;
    private String cdisplayName;
    private String bdisplayflag;
    private String bDataFlag;
    private String ctitle;
    private String bimportflag;
    private Integer nimportno;
    private Integer nimportLen;
    private String bexportflag;
    private Integer nexportno;
    private Integer nexportLen;
    private String bisNumber;
    private String cCustField;
    private String cFormatStr;
    private String cOperator;
    private String creduced;

    public FileFormatBean() {
    }

    public FileFormatBean(Long id) {
        this.id = id;
    }

    public FileFormatBean(Long id, String ctype, Integer nseqno, String cfieldName, String cdisplayName, String bdisplayflag, String bDataFlag, String ctitle, String bimportflag, Integer nimportno, Integer nimportLen, String bexportflag, Integer nexportno, Integer nexportLen, String bisNumber, String cCustField, String cFormatStr, String cOperator, String creduced) {
        setValues(id,ctype,nseqno,cfieldName,cdisplayName,bdisplayflag,bDataFlag,ctitle,bimportflag,nimportno,nimportLen,bexportflag,nexportno,nexportLen
                ,bisNumber,cCustField,cFormatStr,cOperator,creduced);
    }
    public void setValues(Long id, String ctype, Integer nseqno, String cfieldName, String cdisplayName, String bdisplayflag, String bDataFlag,
                          String ctitle, String bimportflag, Integer nimportno, Integer nimportLen,
                          String bexportflag, Integer nexportno, Integer nexportLen,
                          String bisNumber, String cCustField, String cFormatStr, String cOperator, String creduced) {
        this.id = id;
        this.ctype = ctype;
        this.nseqno = nseqno;
        this.cfieldName = cfieldName;
        this.cdisplayName = cdisplayName;
        this.bdisplayflag = bdisplayflag;
        this.bDataFlag = bDataFlag;
        this.ctitle = ctitle;
        this.bimportflag = bimportflag;
        this.nimportno = nimportno;
        this.nimportLen = nimportLen;
        this.bexportflag = bexportflag;
        this.nexportno = nexportno;
        this.nexportLen = nexportLen;
        this.bisNumber = bisNumber;
        this.cCustField = cCustField;
        this.cFormatStr = cFormatStr;
        this.cOperator = cOperator;
        this.creduced = creduced;
    }


    protected FileFormatBean(Parcel in) {
        ctype = in.readString();
        cfieldName = in.readString();
        cdisplayName = in.readString();
        bdisplayflag = in.readString();
        bDataFlag = in.readString();
        ctitle = in.readString();
        bimportflag = in.readString();
        bexportflag = in.readString();
        bisNumber = in.readString();
        cCustField = in.readString();
        cFormatStr = in.readString();
        cOperator = in.readString();
        creduced = in.readString();
    }



    public void clear() {
        this.ctype = "";
        this.nseqno = 0;
        this.cfieldName = "";
        this.cdisplayName = "";
        this.bdisplayflag = "N";
        this.bDataFlag = "N";
        this.ctitle = "";
        this.bimportflag = "N";
        this.nimportno = 0;
        this.nimportLen = 0;
        this.bexportflag = "N";
        this.nexportno = 0;
        this.nexportLen = 0;
        this.bisNumber = "N";
        this.cCustField = "";
        this.cFormatStr = "";
        this.cOperator = "";
        this.creduced = "";
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCtype() {
        return ctype;
    }

    public void setCtype(String ctype) {
        this.ctype = ctype;
    }

    public Integer getNseqno() {
        return nseqno;
    }

    public void setNseqno(Integer nseqno) {
        this.nseqno = nseqno;
    }

    public String getCfieldName() {
        return cfieldName;
    }

    public void setCfieldName(String cfieldName) {
        this.cfieldName = cfieldName;
    }

    public String getCdisplayName() {
        return cdisplayName;
    }

    public void setCdisplayName(String cdisplayName) {
        this.cdisplayName = cdisplayName;
    }

    public String getBdisplayflag() {
        return bdisplayflag;
    }

    public void setBdisplayflag(String bdisplayflag) {
        this.bdisplayflag = bdisplayflag;
    }

    public String getBDataFlag() {
        return bDataFlag;
    }

    public void setBDataFlag(String bDataFlag) {
        this.bDataFlag = bDataFlag;
    }

    public String getCtitle() {
        return ctitle;
    }

    public void setCtitle(String ctitle) {
        this.ctitle = ctitle;
    }

    public String getBimportflag() {
        return bimportflag;
    }

    public void setBimportflag(String bimportflag) {
        this.bimportflag = bimportflag;
    }

    public Integer getNimportno() {
        return nimportno;
    }

    public void setNimportno(Integer nimportno) {
        this.nimportno = nimportno;
    }

    public Integer getNimportLen() {
        return nimportLen;
    }

    public void setNimportLen(Integer nimportLen) {
        this.nimportLen = nimportLen;
    }

    public String getBexportflag() {
        return bexportflag;
    }

    public void setBexportflag(String bexportflag) {
        this.bexportflag = bexportflag;
    }

    public Integer getNexportno() {
        return nexportno;
    }

    public void setNexportno(Integer nexportno) {
        this.nexportno = nexportno;
    }

    public Integer getNexportLen() {
        return nexportLen;
    }

    public void setNexportLen(Integer nexportLen) {
        this.nexportLen = nexportLen;
    }

    public String getBisNumber() {
        return bisNumber;
    }

    public void setBisNumber(String bisNumber) {
        this.bisNumber = bisNumber;
    }

    public String getCCustField() {
        return cCustField;
    }

    public void setCCustField(String cCustField) {
        this.cCustField = cCustField;
    }

    public String getCFormatStr() {
        return cFormatStr;
    }

    public void setCFormatStr(String cFormatStr) {
        this.cFormatStr = cFormatStr;
    }

    public String getCOperator() {
        return cOperator;
    }

    public void setCOperator(String cOperator) {
        this.cOperator = cOperator;
    }

    public String getCreduced() {
        return creduced;
    }

    public void setCreduced(String creduced) {
        this.creduced = creduced;
    }

}
